eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest